export const EBS_CONNECT_SUPABASE_URL = process.env.EBS_CONNECT_SUPABASE_URL;
export const EBS_CONNECT_SUPABASE_KEY = process.env.EBS_CONNECT_SUPABASE_KEY;
export const EBS_CONNECT_SUPABASE_CHANNEL = process.env.EBS_CONNECT_SUPABASE_CHANNEL;
export const EBS_CONNECT_SUPABASE_SCHEMA = process.env.EBS_CONNECT_SUPABASE_SCHEMA;
export const EBS_CONNECT_SUPABASE_TABLE = process.env.EBS_CONNECT_SUPABASE_TABLE;
export const EBS_CONNECT_SYNC = process.env.EBS_CONNECT_SYNC;
