export const SYSTEM_ADMIN_DISPLAY_NAME = process.env.SYSTEM_ADMIN_DISPLAY_NAME;
export const SYSTEM_ADMIN_PHONE_NUMBER = process.env.SYSTEM_ADMIN_PHONE_NUMBER;
export const SYSTEM_ADMIN_SPOT = process.env.SYSTEM_ADMIN_SPOT;
